### ISSUE TITLE
can you give me the raw data, thankyou

### ISSUE THREAD

**Issue by geekvc** [yihui-he/region-proposal-network#1]
ultrasound.py
data_path='/mnt/data1/yihuihe/mnc/'

class rawData:
    def __init__(self, split=.9):
        self.imdb=np.load(data_path+'data.npy')
        self.maskdb=np.load(data_path+'maskdb.npy')
        self.roidb=np.load(data_path+'roidb.npy')
        self.mask=np.load(data_path+'mask.npy')
        self.total=self.imdb.shape[0]

File "test.py", line 52, in <module>
    solve=solverWrapper()
  File "test.py", line 25, in __init__
    self.solver=caffe.SGDSolver("solver.prototxt")
  File "/mnt/geekvc/region-proposal-network/fasterRCNN_data.py", line 45, in setup
    self.data_queue=rawData()
  File "/mnt/geekvc/region-proposal-network/ultrasound.py", line 10, in __init__
    self.imdb=np.load(data_path+'data.npy')
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 370, in load
    fid = open(file, "rb")
IOError: [Errno 2] No such file or directory: '/mnt/data1/yihuihe/mnc/data.npy'

**Comment by ethanhe42** [comment]
@geekvc Sorry I can't find it. Actually you can create your own data.npy. It's just numpy array containing images.

**Comment by geekvc** [comment]
Thank you very much!
I have known how to do it.
